name = "omniknight"
main = "dist/index.mjs"

workers_dev = true
compatibility_date = "2022-11-30"
compatibility_flags = []

durable_objects.bindings = [
    { name = "channels", class_name = "Channel" }
]

[[migrations]]
tag = "v1"
new_classes = ["Chat"]

[[migrations]]
tag = "v2"
renamed_classes = [{from= "Chat", to= "Channel"}]

[build]
command = "node build.mjs"
